alias nixconf   'sudo nano /etc/nixos/configuration.nix'
alias hwconf    'sudo nano /etc/nixos/hardware-configuration.nix'
alias coreconf  'sudo nano /etc/nixos/system/core.nix'
alias servconf  'sudo nano /etc/nixos/system/services.nix'
alias devconf   'sudo nano /etc/nixos/applications/dev_packages.nix'
alias appsconf  'sudo nano /etc/nixos/applications/everyday_life_packages.nix'
alias niriconf  'sudo nano /etc/nixos/desktop/niri.nix'
alias shellconf 'sudo nano /etc/nixos/desktop/shell.nix'
alias fishconf  'sudo nano /etc/nixos/desktop/fish.nix'

alias nrs 'sudo nixos-rebuild switch'
alias nrb 'sudo nixos-rebuild boot'
alias nrt 'sudo nixos-rebuild test'
alias nrc 'sudo nixos-rebuild switch'

alias nchu 'sudo nix-channel --update'
alias ngc  'sudo nix-collect-garbage -d'
alias nsearch 'nix search nixpkgs'

alias ll 'ls -lah'
alias gs 'git status'
alias gc 'git commit'
alias gp 'git push'